### ISSUE TITLE
the terminal shows "Camera [4]'s data is too late"

### ISSUE THREAD

**Issue by manlianhhd** [HesaiTechnology/Pandora_Projection_ROS#4]
I have run the pandora_projection_ros, and the terminal shows "Camera [4]'s data is too late" . Sometime, it also shows "Camera [1]'s data is too late, "Camera [2]'s data is too late, "Camera [3]'s data is too late,"Camera [4]'s data is too late. I want to know how to solve this problem. Thank you.

**Comment by hesaiwuxiaozhou** [comment]
It is OK during the first few seconds of openning pandora_projection_ros.

In another case， if there is something very closed lidar, it will happen too.
